name: Process Customers Workflow

on:
  push:
    branches:
      - main

jobs:
  process_customers
    runs-on: ubuntu-latest

inputs:
      customers:
        description: 'Comma-separated list of customer names'
        required: true
 env:
  CUSTOMER_NAMES: ${{ inputs.customers }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Process Customer Names
        run: |
          IFS=',' read -ra CUSTOMER_ARRAY <<< "$CUSTOMER_NAMES"
          for customer in "${CUSTOMER_ARRAY[@]}"; do
            echo "Processing customer: $customer"
            # Add your custom logic here
          done

 
