name: Dynamic List Example
on:
  push:
    branches:
      - main
jobs:
  dynamic_job:
    runs-on: ubuntu-latest
    inputs:
      my_dynamic_list:
        description: A dynamic list of values
        required: true
    steps:
      - uses: actions/checkout@v4
      - name: Show Dynamic List
        run: |
          echo "Dynamic List: ${{ inputs.my_dynamic_list }}"
 
